steps:
  - name: "gcr.io/cloud-builders/yarn"
    id: "install"
    args: ["install"]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "decrypt .env"
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --project=bundle-size-tools
      - --keyring=deploy
      - --key=env
  - name: "gcr.io/cloud-builders/yarn"
    waitFor: ["decrypt .env"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then yarn global add serverless && serverless deploy; else exit 0; fi
