service: bundle-size-charter 

provider:
  name: google
  runtime: nodejs8
  project: bundle-size-tools 
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: chartSize
    events:
      - http: path
