service: bundle-size-charter # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs8
  project: cds-snc 
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: handleEvent
    events:
      - http: path
